baseURL       = "https://metastructure.naruki-ichihara.com"
languageCode  = "en-us"
title         = "Metastructure lab"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Members"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Research projects"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Publications"
    url     = "https://naruki-ichihara.com/"
    weight  = 5
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 6

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "metastructure"
  author = "Naruki Ichihara"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/f/xrgdggyb"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Category"
    placeholder_about_the_project = "Body"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "rp"
      title  = "Research projects"
    [[params.contactForm.projectType]]
      value = "tc"
      title  = "Technical consultants"
    [[params.contactForm.projectType]]
      value = "ot"
      title  = "Others"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background_2.jpg"
    heading               = "Metastructure Lab"
    tagline               = "Hi, we are"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"
    heading_sub           = "Metastructure"
    description           = "We explore an emerging class of structure, metastructure. Metastructure consists of metamaterials that deliver unique functionalities through their detailed structural design. "

  [params.blog]
    enable    = true
    title     = "News feed"
    subtitle  = ""

  [params.portfolio]
    enable    = false
    title     = "Works"
    subtitle  = ""

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "1-8-14 Kanda-surugadai, Chiyoda, Tokyo, 101-8308, JAPAN"
      phone   = "(+81)3-3259-0746"
      email   = "ichihara.naruki@nihon-u.ac.jp"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About us"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Research projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "#"
        [[params.footer.social.link]]
          name = "Twetter"
          url  = "#"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "#"
      # Footer Service
      #[params.footer.service]
      #  title       = "We help brands:"
      #  description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"